# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Sérgio Costa
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://a-sac.me
baseurl: "/a-sac"

google_analytics: UA-52446115-1
repo: http://github.com/a-sac/a-sac.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Sérgio COSTA
  job: Software Engineer's student
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee.
        Long talks lover!"
  thumb: /images/author.jpeg
  email: asergioalvesc@gmail.com
  url: 
  github: https://github.com/a-sac
  twitter: https://twitter.com/sergio_alvesc
  facebook: https://facebook.com/asergioalvesc
  linkedin: https://linkedin.com/in/asergioalvesc

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
